import { NetworkTopology } from '../types/network';
import { topologyToXml } from './defaultTopology';

export interface TopologyExportFormats {
  xml: string;
  json: string;
  adjacencyMatrixCsv: string;
  graphvizDot: string;
  ns2TclScript: string;
  ciscoRouterConfig: string;
}

export function generateAllTopologyExports(topology: NetworkTopology): TopologyExportFormats {
  // 1. XML format
  const xml = topologyToXml(topology);

  // 2. JSON format
  const json = JSON.stringify(topology, null, 2);

  // 3. Adjacency Matrix CSV
  const nodeIds = topology.nodes.map((n) => n.id);
  const matrix: Record<string, Record<string, number | string>> = {};
  nodeIds.forEach((u) => {
    matrix[u] = {};
    nodeIds.forEach((v) => {
      matrix[u][v] = u === v ? 0 : 'INF';
    });
  });
  topology.edges.forEach((e) => {
    if (matrix[e.source] && matrix[e.destination]) {
      matrix[e.source][e.destination] = e.cost;
      matrix[e.destination][e.source] = e.cost;
    }
  });

  let csv = 'Router,' + nodeIds.join(',') + '\n';
  nodeIds.forEach((u) => {
    csv += u + ',' + nodeIds.map((v) => matrix[u][v]).join(',') + '\n';
  });

  // 4. Graphviz DOT syntax
  let dot = 'graph NetworkTopology {\n';
  dot += '  graph [rankdir=LR, bgcolor="#020617"];\n';
  dot += '  node [shape=circle, style=filled, fillcolor="#0f172a", fontcolor="#38bdf8", fontname="Courier", color="#38bdf8"];\n';
  dot += '  edge [color="#64748b", fontcolor="#f59e0b", fontname="Courier", fontsize=10];\n\n';
  topology.nodes.forEach((n) => {
    dot += `  ${n.id} [label="${n.id}\\n${n.name}"];\n`;
  });
  dot += '\n';
  topology.edges.forEach((e) => {
    dot += `  ${e.source} -- ${e.destination} [label="cost: ${e.cost}, ${e.bandwidthMbps || 100}Mb"];\n`;
  });
  dot += '}\n';

  // 5. NS-2 / NS-3 Network Simulator TCL Script
  let tcl = `# =====================================================================\n`;
  tcl += `# NS-2 Network Simulator Script Generated by Network Routing Analyzer\n`;
  tcl += `# Experiment: Dijkstra & Distance Vector Performance Evaluation\n`;
  tcl += `# =====================================================================\n\n`;
  tcl += `set ns [new Simulator]\n\n`;
  tcl += `# Open trace and NAM output files\n`;
  tcl += `set tracefile [open out.tr w]\n`;
  tcl += `$ns trace-all $tracefile\n`;
  tcl += `set namfile [open out.nam w]\n`;
  tcl += `$ns namtrace-all $namfile\n\n`;
  tcl += `# Create Router Nodes\n`;
  topology.nodes.forEach((n) => {
    tcl += `set n(${n.id}) [$ns node]\n`;
  });
  tcl += `\n# Create Duplex Links with Metric Weights\n`;
  topology.edges.forEach((e) => {
    const bw = e.bandwidthMbps || 100;
    const delay = e.delayMs || (e.cost * 4);
    tcl += `$ns duplex-link $n(${e.source}) $n(${e.destination}) ${bw}Mb ${delay}ms DropTail\n`;
    tcl += `$ns cost $n(${e.source}) $n(${e.destination}) ${e.cost}\n`;
    tcl += `$ns cost $n(${e.destination}) $n(${e.source}) ${e.cost}\n`;
  });
  tcl += `\n# Setup Routing Protocol: LinkState (Dijkstra) or DistanceVector (Bellman-Ford)\n`;
  tcl += `$ns rtproto DV\n\n`;
  tcl += `# Setup UDP Agent & CBR traffic generator on Source R1\n`;
  if (topology.nodes.length >= 2) {
    const src = topology.nodes[0].id;
    const dst = topology.nodes[topology.nodes.length - 1].id;
    tcl += `set udp0 [new Agent/UDP]\n`;
    tcl += `$ns attach-agent $n(${src}) $udp0\n`;
    tcl += `set cbr0 [new Application/Traffic/CBR]\n`;
    tcl += `$cbr0 set packetSize_ 1000\n`;
    tcl += `$cbr0 set interval_ 0.01\n`;
    tcl += `$cbr0 attach-agent $udp0\n\n`;
    tcl += `set null0 [new Agent/Null]\n`;
    tcl += `$ns attach-agent $n(${dst}) $null0\n`;
    tcl += `$ns connect $udp0 $null0\n\n`;
    tcl += `$ns at 0.5 "$cbr0 start"\n`;
    tcl += `$ns at 4.5 "$cbr0 stop"\n`;
    tcl += `$ns at 5.0 "finish"\n\n`;
  }
  tcl += `proc finish {} {\n`;
  tcl += `    global ns tracefile namfile\n`;
  tcl += `    $ns flush-trace\n`;
  tcl += `    close $tracefile\n`;
  tcl += `    close $namfile\n`;
  tcl += `    exec nam out.nam &\n`;
  tcl += `    exit 0\n`;
  tcl += `}\n\n`;
  tcl += `$ns run\n`;

  // 6. Cisco IOS Router CLI Configuration snippet
  let cisco = `! =========================================================\n`;
  cisco += `! Cisco IOS Router Configuration Snippet (OSPF & RIP)\n`;
  cisco += `! Generated for CN Lab External Project Architecture\n`;
  cisco += `! =========================================================\n\n`;
  topology.nodes.forEach((n, idx) => {
    cisco += `! Configuration for Router ${n.id}\n`;
    cisco += `hostname ${n.id}\n`;
    cisco += `enable secret cisco123\n`;
    cisco += `interface Loopback0\n`;
    cisco += ` ip address 10.0.${idx + 1}.1 255.255.255.255\n`;
    cisco += `!\n`;
    const routerEdges = topology.edges.filter((e) => e.source === n.id || e.destination === n.id);
    routerEdges.forEach((e, ifIndex) => {
      const neighbor = e.source === n.id ? e.destination : e.source;
      cisco += `interface GigabitEthernet0/${ifIndex}\n`;
      cisco += ` description Link to ${neighbor} (Cost: ${e.cost})\n`;
      cisco += ` ip address 192.168.${idx + 1}${ifIndex + 1}.1 255.255.255.0\n`;
      cisco += ` ip ospf cost ${e.cost}\n`;
      cisco += ` no shutdown\n`;
      cisco += `!\n`;
    });
    cisco += `router ospf 1\n`;
    cisco += ` router-id 10.0.${idx + 1}.1\n`;
    cisco += ` network 192.168.0.0 0.0.255.255 area 0\n`;
    cisco += `!\n`;
  });

  return {
    xml,
    json,
    adjacencyMatrixCsv: csv,
    graphvizDot: dot,
    ns2TclScript: tcl,
    ciscoRouterConfig: cisco,
  };
}
